from models.connect import Connect


class BookService:
    book_connection: Connect = Connect("BookService")

    @staticmethod
    def reset_all_table():
        sql = """
        drop table books;
        drop table book_category;
        drop table sub_category;
        drop TABLE global_category;
        """

        BookService.book_connection.cursor.execute(sql)
        BookService.book_connection.connection.commit()

        sql = """
        CREATE TABLE books
        (
            id                              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title                           VARCHAR,
            author                          VARCHAR,
            lang                            VARCHAR(100),
            document_size                   VARCHAR(200),
            year_of_publication             INTEGER,
            publishing_house                VARCHAR(200),
            country                         VARCHAR(200),
            number_of_pages                 INTEGER,
            availability_in_the_library     VARCHAR(50),
            availability_in_electronic_form VARCHAR(50),
            added                           VARCHAR(200),
            classification_id               INT,
            document_type                   VARCHAR(200),
            link_to_book                    VARCHAR(200),
            sub_category                    INT,
            global_category                 INT
        );
        CREATE TABLE global_category(
            id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category_title      VARCHAR UNIQUE NOT NULL
        );
        
        CREATE TABLE sub_category(
            id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sub_title           VARCHAR UNIQUE NOT NULL ,
            global_id           INT references global_category(id)
        );
        CREATE TABLE book_category(
            id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category_title      VARCHAR UNIQUE NOT NULL,
        sub_id              INT references sub_category(id)
        );
        """
        BookService.book_connection.cursor.execute(sql)
        BookService.book_connection.connection.commit()

    @staticmethod
    def insert(book):
        sql = """INSERT INTO books (title, author, lang, document_size, year_of_publication, publishing_house, 
        country, number_of_pages, availability_in_the_library, availability_in_electronic_form, added, 
        classification_id, document_type, link_to_book, sub_category, global_category) 
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) """
        record_to_insert = (
            book.title, book.author, book.lang, book.document_size, book.year_of_publication, book.publishing_house,
            book.country, book.number_of_pages, book.availability_in_the_library, book.availability_in_electronic_form,
            book.added, book.classification_id, book.document_type, book.link, book.sub_category, book.global_category)

        BookService.book_connection.cursor.execute(sql, record_to_insert)
        BookService.book_connection.connection.commit()

    @staticmethod
    def find_by_title(title):
        like_title = """ '%""" + title + """%';"""
        sql = """SELECT * FROM books WHERE LOWER(title) LIKE""" + like_title.lower()

        print(sql)
        BookService.book_connection.cursor.execute(sql)
        tuple_book = BookService.book_connection.cursor.fetchall()
        return tuple_book

    @staticmethod
    def find_book_by_ids(request_books: str):
        request_books = request_books.replace(" ", ", ")
        sql = """SELECT * FROM books WHERE id in (""" + request_books + """)"""
        BookService.book_connection.cursor.execute(sql)

        tuple_book = BookService.book_connection.cursor.fetchall()
        return tuple_book

    @staticmethod
    def find_books_by_book_category(category_id):
        sql = """SELECT * FROM books WHERE classification_id = %s"""
        BookService.book_connection.cursor.execute(sql, (category_id,))

        tuple_book = BookService.book_connection.cursor.fetchall()
        return tuple_book

    @staticmethod
    def find_books_by_author(author: str):
        like_author = """ '%""" + author + """%';"""
        sql = """SELECT * FROM books WHERE LOWER(author) LIKE""" + like_author.lower()
        BookService.book_connection.cursor.execute(sql)
        print(sql)
        tuple_book = BookService.book_connection.cursor.fetchall()
        return tuple_book

    @staticmethod
    def replace_c():
        sql_select = """UPDATE books SET title = REPLACE(title ,'С++', 'C++' ) WHERE title LIKE '%С++%';
                        UPDATE books SET title = REPLACE(title ,'С#', 'C#' ) WHERE title LIKE '%С#%';"""
        BookService.book_connection.cursor.execute(sql_select)
        BookService.book_connection.connection.commit()

    @staticmethod
    def clean_dataset():
        sql_drop = "TRUNCATE TABLE books;"
        BookService.book_connection.cursor.execute(sql_drop)
        BookService.book_connection.connection.commit()

    @staticmethod
    def finalize():
        BookService.book_connection.finalize()
