CREATE TABLE books
(
    id                              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                           VARCHAR,
    author                          VARCHAR,
    lang                            VARCHAR(100),
    document_size                   VARCHAR(200),
    year_of_publication             INTEGER,
    publishing_house                VARCHAR(200),
    country                         VARCHAR(200),
    number_of_pages                 INTEGER,
    availability_in_the_library     VARCHAR(50),
    availability_in_electronic_form VARCHAR(50),
    added                           VARCHAR(200),
    classification_id               INT,
    document_type                   VARCHAR(200),
    link_to_book                    VARCHAR(200),
    sub_category                    INT,
    global_category                 INT
);


drop table books;


SELECT * FROM books WHERE title LIKE '%C++%'; -- Engl 11
SELECT * FROM books WHERE title LIKE '%С++%'; -- RU   10


SELECT * FROM books WHERE title LIKE '%C#%';
SELECT * FROM books WHERE title LIKE '%С#%';

select * from books;

SELECT title from books GROUP BY title;
SELECT * from books WHERE title='Захист інформації на об’єктах інформаційної діяльності. Створення комплексу технічного захисту інформації. Порядок розроблення та впровадження заходів із захисту інформації';


UPDATE books SET title = REPLACE(title ,'С++', 'C++' ) WHERE title LIKE '%С++%';
UPDATE books SET title = REPLACE(title ,'С#', 'C#' ) WHERE title LIKE '%С#%';

SELECT * FROM books WHERE LOWER(title) LIKE '%c++%';

SELECT * FROM books WHERE LOWER(title) LIKE '%c++%';
-- select * from books_final;


-- UPDATE Person Set fullName=?, yearOfBirth=? WHERE person_id=?
-- SELECT classification, COUNT(*) as count FROM books  GROUP BY classification ;


CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    username VARCHAR(200)

);

SELECT * FROM users;

CREATE TABLE query(
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      search_string VARCHAR UNIQUE ,
      string_books_id VARCHAR
);
drop TABLE query;
select * from query;


drop TABLE global_category;
drop table sub_category;
drop table book_category;

select * from global_category;
CREATE TABLE global_category(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_title      VARCHAR UNIQUE NOT NULL
);

CREATE TABLE sub_category(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_title           VARCHAR UNIQUE NOT NULL ,
    global_id           INT references global_category(id)
);

select * from sub_category;


CREATE TABLE book_category(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_title      VARCHAR UNIQUE NOT NULL,
    sub_id              INT references sub_category(id)

);
select * from book_category;


SELECT * from book_category WHERE sub_id = 1;

INSERT INTO global_category (category_title) values('андрей');
INSERT INTO sub_category (sub_title, global_id) values('андрей_sub', 1);
INSERT INTO sub_category (sub_title, global_id) values('андрей_sub2', 1);


SELECT * from sub_category WHERE global_id = 2;

SELECT * from global_category;


